// Auth Types
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERRORS = 'CLEAR_ERRORS';
export const LOGOUT = 'LOGOUT';

// Admin Types
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_USER_LOADED = 'ADMIN_USER_LOADED';
export const SET_ADMIN_AUTH_LOADING = 'SET_ADMIN_AUTH_LOADING';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';
export const CLEAR_ADMIN_ERRORS = 'ADMIN_CLEAR_ERRORS';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const STUDENT_ERROR = 'STUDENT_ERROR';
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
export const ATTENDANCE_ERROR = 'ATTENDANCE_ERROR';
